Add pkcs11 support to get_security_files
ros2/rmw_dds_common pull request #66
Opened 2023-01-10 12:05 UTC by MiguelCompany

This implements ros2/design#332

2023-02-14 14:53 UTC, ruffsl approved these changes

2023-02-14 14:54 UTC, ruffsl commented
Ping @clalancette or @mikaelarguedas ? Good to merge?

2023-02-21 22:29 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-02-16/29927/1

2023-07-20 08:11 UTC, SubaruArai commented
@MiguelCompany any update on this pr?

Or should we wait [REP-2015](https://github.com/ros-infrastructure/rep/pull/375) to be approved first?

2023-07-20 08:31 UTC, MiguelCompany commented
@SubaruArai I don't know what the process is. I guess we should wait for [REP-2015](https://github.com/ros-infrastructure/rep/pull/375), but I am just an external contributor, and I suppose that someone in the ROS 2 team should answer that.

Maybe @clalancette or @gbiggs can clarify?

2024-04-04 14:26 UTC, ahcorde requested changes
This PR is stuck for a while, are we planning to merge this before feature freeze? @clalancette ?

 I'm missing some tests in the `test_security.cpp` file. Do you mind to add them?

2024-04-05 07:03 UTC, MiguelCompany commented
@ahcorde I just rebased this. Will try to add tests in the `test_security.cpp` file

2024-04-05 09:24 UTC, MiguelCompany commented
@ahcorde I updated the tests in `test_security.cpp`

2024-04-05 18:43 UTC, ahcorde requested changes

2024-04-05 18:43 UTC, ahcorde commented on rmw_dds_common/test/test_security.cpp
> +template<size_t N>
include `<cstddef>`

2024-04-05 18:43 UTC, ahcorde commented on rmw_dds_common/src/security.cpp
> +  // Key: the security attribute
```suggestion
    std::vector<std::pair<std::string, security_file_processor>>;

  // Key: the security attribute
```

2024-04-05 18:43 UTC, ahcorde commented on rmw_dds_common/src/security.cpp
> +  for (const std::pair<const std::string,
#include `<utility>`

2024-04-05 19:05 UTC, MiguelCompany commented on rmw_dds_common/test/test_security.cpp
> +template<size_t N>
305e4cc88ca6b8f59705c4c445d609ede74ab0fb

2024-04-05 19:05 UTC, MiguelCompany commented on rmw_dds_common/src/security.cpp
> +  // Key: the security attribute
305e4cc88ca6b8f59705c4c445d609ede74ab0fb

2024-04-05 19:06 UTC, MiguelCompany commented on rmw_dds_common/src/security.cpp
> +  for (const std::pair<const std::string,
Was already there (line 19)

2024-04-05 19:58 UTC, clalancette commented
Here is CI for this:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20766)](http://ci.ros2.org/job/ci_linux/20766/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15064)](http://ci.ros2.org/job/ci_linux-aarch64/15064/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21447)](http://ci.ros2.org/job/ci_windows/21447/)

2024-04-08 11:54 UTC, clalancette commented
A couple more pieces of CI, then I think this is good to go:

* RHEL [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=630)](http://ci.ros2.org/job/ci_linux-rhel/630/)
* Clang [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux_clang_libcxx&build=67)](http://ci.ros2.org/job/ci_linux_clang_libcxx/67/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21462)](http://ci.ros2.org/job/ci_windows/21462/)

2024-04-08 15:31 UTC, clalancette approved these changes

2024-04-08 15:35 UTC, ahcorde approved these changes

2024-04-08 17:25 UTC, clalancette commented
All of the warnings here were also in the nightlies, so going ahead and merging this one in.

2024-04-08 17:26 UTC, merged